<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><ApplicationIcon>logo.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>ChickenDist</AssemblyName>
    <RootNamespace>ChickenDist</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>9.0</LangVersion>
    <ApplicationDefaultFont>Segoe UI, 9.75pt</ApplicationDefaultFont>
    <StartupObject>ChickenDist.Program</StartupObject>
    <CodePage>65001</CodePage>
    <Utf8Output>true</Utf8Output>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <EmbeddedResource Include="Forms\driver_sales.html" />
  </ItemGroup>
</Project>
